/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Kitap;

/**
 *
 * @author msi
 */
public class KitapEkle extends javax.swing.JFrame {

    /**
     * Creates new form kitapEkle
     */
    KitapPanel kitappanel;
    
    public KitapEkle() {
        ImageIcon img = new ImageIcon("C:\\Users\\Lenovo\\Desktop\\kutuphaneotomasyonu\\src\\main\\java\\view\\kutuphaneIcon.png");
        this.setIconImage(img.getImage());
        this.setTitle("Kitap Ekle");
        initComponents();
    }
    
    public KitapEkle(KitapPanel kitappanel) {
        ImageIcon img = new ImageIcon("C:\\Users\\Lenovo\\Desktop\\kutuphaneotomasyonu\\src\\main\\java\\view\\kutuphaneIcon.png");
        this.setIconImage(img.getImage());
        this.setTitle("Kitap Ekle");
        initComponents();
        this.kitappanel = kitappanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitapAdi = new javax.swing.JLabel();
        kitapYazari = new javax.swing.JLabel();
        kitapEkleButon = new javax.swing.JButton();
        kitapSayfa = new javax.swing.JLabel();
        kitapEkleYayinevi = new javax.swing.JTextField();
        kitapEkleKategori = new javax.swing.JComboBox<>();
        kitapKategori = new javax.swing.JLabel();
        kitapYayinevi = new javax.swing.JLabel();
        kitapEkleAdi = new javax.swing.JTextField();
        kitapEkleYazari = new javax.swing.JTextField();
        kitapEkleSayfa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kitapAdi.setText("KİTAP ADI:");

        kitapYazari.setText("KİTAP YAZARI:");

        kitapEkleButon.setText("Kitap Ekle");
        kitapEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					kitapEkleButonActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        kitapSayfa.setText("KİTAP SAYFA:");

        kitapEkleKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bir Kategori Seçiniz", "Bilim&Mühendislik", "Çocuk Kitapları", "Dini", "Edebi Kitaplar", "Eğitim", "Kişisel Gelişim", "Sağlık", "Siyasi", "Tarihi", " ", " " }));
        kitapEkleKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapEkleKategoriActionPerformed(evt);
            }
        });

        kitapKategori.setText("KİTAP KATEGORİ:");

        kitapYayinevi.setText("KİTAP YAYINEVİ:");

        kitapEkleAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapEkleAdiActionPerformed(evt);
            }
        });

        kitapEkleYazari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapEkleYazariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kitapYayinevi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kitapKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kitapSayfa)
                        .addComponent(kitapYazari))
                    .addComponent(kitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kitapEkleYayinevi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kitapEkleAdi)
                        .addComponent(kitapEkleYazari, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kitapEkleSayfa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kitapEkleKategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kitapEkleButon)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapAdi)
                    .addComponent(kitapEkleAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapYazari)
                    .addComponent(kitapEkleYazari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapSayfa)
                    .addComponent(kitapEkleSayfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapKategori)
                    .addComponent(kitapEkleKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitapYayinevi)
                    .addComponent(kitapEkleYayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(kitapEkleButon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitapEkleButonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_kitapEkleButonActionPerformed
        Kitap k=new Kitap();
        k.kitapAdi = kitapEkleAdi.getText();
        k.kitapYazari=kitapEkleYazari.getText();
        k.kitapSayfa=Integer.parseInt(kitapEkleSayfa.getText());
        k.kitapKategori=kitapEkleKategori.getSelectedItem().toString();
        k.kitapYayinevi=kitapEkleYayinevi.getText();

        if(k.kitapAdi.equals("") || k.kitapYazari.equals("") || k.kitapSayfa == 0 || k.kitapKategori.equals("") || k.kitapYayinevi.equals("")){
            String hataMesajı = "";
            if(k.kitapAdi.equals(""))
            hataMesajı += "Lütfen kitap adı girin..\n";

            if(k.kitapYazari.equals(""))
            hataMesajı += "Lütfen kitap yazarını girin..\n";

            if(k.kitapSayfa == 0)
            hataMesajı += "Lütfen kitabın sayfasını girin..\n";

            if(k.kitapKategori.equals(""))
            hataMesajı += "Lütfen kitabın ait olduğu kategoriyi seçin..\n";

            if(k.kitapYayinevi.equals(""))
            hataMesajı += "Lütfen kitabın yayınevini girin..\n";

            JOptionPane.showMessageDialog(rootPane, hataMesajı);
        }else {
            try {
                k.ekle(k);
                System.out.println("Kitap başarıyla eklendi..");
                kitappanel.tabloYenile();
                this.setVisible(false);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_kitapEkleButonActionPerformed

    private void kitapEkleKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapEkleKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapEkleKategoriActionPerformed

    private void kitapEkleAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapEkleAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapEkleAdiActionPerformed

    private void kitapEkleYazariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapEkleYazariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapEkleYazariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel kitapAdi;
    private javax.swing.JTextField kitapEkleAdi;
    private javax.swing.JButton kitapEkleButon;
    private javax.swing.JComboBox<String> kitapEkleKategori;
    private javax.swing.JTextField kitapEkleSayfa;
    private javax.swing.JTextField kitapEkleYayinevi;
    private javax.swing.JTextField kitapEkleYazari;
    private javax.swing.JLabel kitapKategori;
    private javax.swing.JLabel kitapSayfa;
    private javax.swing.JLabel kitapYayinevi;
    private javax.swing.JLabel kitapYazari;
    // End of variables declaration//GEN-END:variables
}
