/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Kitap;

/**
 *
 * @author msi
 */
public class KitapPanel extends javax.swing.JPanel {

    /**
     * Creates new form KitapPanel
     */
    
    int seciliSatirSirasi;
    String seciliKitapID;
    
    public KitapPanel() throws Exception {
        initComponents();
        tabloYenile();
    }
    public void tabloYenile() throws Exception{
        Kitap k = new Kitap();
        ArrayList<Kitap> kitaplar = k.listele();
        tabloyuDoldur(kitaplar);
    }
    
    public void tabloyuDoldur(ArrayList<Kitap> kitaplar)
    {
          
          String veriler[][]=new String[kitaplar.size()][];

          for (int i = 0; i < kitaplar.size(); i++) {     
             veriler[i]=new String[]{                                   
                kitaplar.get(i).kitapID +"",
                kitaplar.get(i).kitapAdi,
                kitaplar.get(i).kitapYazari,
                kitaplar.get(i).kitapSayfa +"",
                kitaplar.get(i).kitapYayinevi,
                kitaplar.get(i).kitapKategori                    
             };                  
         }
          String [] tabloBaslik = new String[] {"Kitap ID", "Kitap Adı", "Kitap Yazarı", "Sayfa Sayısı", "Kitap Yayınevi", "Kitap Kategori"};
          TableModel tabloModeli=new DefaultTableModel( veriler, tabloBaslik );                                                
          jTable1.setModel(tabloModeli);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aranacakkelime = new javax.swing.JTextField();
        uyeara = new javax.swing.JButton();
        kitapguncelle = new javax.swing.JButton();
        kitapsil = new javax.swing.JButton();
        kitapekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        aranacakkelime.setText(" ");

        uyeara.setText("Ara Beniiiii :)");
        uyeara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyearaActionPerformed(evt);
            }
        });

        kitapguncelle.setText("Kitap Güncelle");
        kitapguncelle.setEnabled(false);
        kitapguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapguncelleActionPerformed(evt);
            }
        });

        kitapsil.setText("Kitap Sil");
        kitapsil.setEnabled(false);
        kitapsil.setName(""); // NOI18N
        kitapsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapsilActionPerformed(evt);
            }
        });

        kitapekle.setText("Yeni Kitap Ekle");
        kitapekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapekleActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aranacakkelime, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uyeara)
                        .addGap(77, 77, 77)
                        .addComponent(kitapguncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kitapsil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kitapekle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aranacakkelime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uyeara)
                    .addComponent(kitapguncelle)
                    .addComponent(kitapsil)
                    .addComponent(kitapekle))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void uyearaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyearaActionPerformed
        String kelime = aranacakkelime.getText().toString();
        System.out.println(kelime);
        try {
            Kitap k = new Kitap();
            ArrayList<Kitap> kitaplar = k.ara(kelime);
            tabloyuDoldur(kitaplar);
        }catch(Exception e) {
            System.out.println("Hata");
        }

    }//GEN-LAST:event_uyearaActionPerformed

    private void kitapguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapguncelleActionPerformed

        try{
            Kitap k = new Kitap();
            k.kitapAdi = jTable1.getValueAt(seciliSatirSirasi, 1).toString();
            k.kitapYazari = jTable1.getValueAt(seciliSatirSirasi, 2).toString();
            k.kitapSayfa = Integer.parseInt(jTable1.getValueAt(seciliSatirSirasi, 3).toString());
            k.kitapYayinevi = jTable1.getValueAt(seciliSatirSirasi, 4).toString();
            k.kitapKategori = jTable1.getValueAt(seciliSatirSirasi, 5).toString();
            
            k.guncelle(Integer.parseInt(seciliKitapID),k);
            System.out.println("Başarılı");
            tabloYenile();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_kitapguncelleActionPerformed

    private void kitapsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapsilActionPerformed
        try{
            Kitap k = new Kitap();
            k.sil(Integer.parseInt(seciliKitapID));
            System.out.println("Başarılı");
            tabloYenile();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_kitapsilActionPerformed

    private void kitapekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapekleActionPerformed
        try {
            KitapEkle kitapEkle= new KitapEkle(this);
            kitapEkle.pack();
            kitapEkle.setLocationRelativeTo(null);
            kitapEkle.setVisible(true);
            kitapEkle.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_kitapekleActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained

    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        seciliSatirSirasi = jTable1.getSelectedRow();
        seciliKitapID = jTable1.getValueAt(seciliSatirSirasi, 0).toString();
        System.out.println(seciliKitapID);

        kitapguncelle.setEnabled(true);
        kitapsil.setEnabled(true);
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        kitapguncelle.enable(true);
        kitapsil.enable(true);
    }//GEN-LAST:event_jTable1PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aranacakkelime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kitapekle;
    private javax.swing.JButton kitapguncelle;
    private javax.swing.JButton kitapsil;
    private javax.swing.JButton uyeara;
    // End of variables declaration//GEN-END:variables
}
