/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Odunc;

/**
 *
 * @author msi
 */
public class OduncPanel extends javax.swing.JPanel {

    /**
     * Creates new form OduncPanel
     */
    
        int seciliSatirSirasi;
        String seciliIslemID;
    
    public OduncPanel() throws Exception{
        initComponents();
        tabloYenile();
    }
    
    public void tabloYenile() throws Exception{
        Odunc k = new Odunc();
        ArrayList<Odunc> odunc = k.listele();
        tabloyuDoldur(odunc);
    }
  
    
    public void tabloyuDoldur(ArrayList<Odunc> oduncler)
    {          
          String veriler[][]=new String[oduncler.size()][];

          for (int i = 0; i < oduncler.size(); i++) {     
             veriler[i]=new String[]{     
                oduncler.get(i).islemID+"",
                oduncler.get(i).kisiAdi,
                oduncler.get(i).kitapAdi,
                oduncler.get(i).emanetTarihi,
                oduncler.get(i).iadeTarihi
                            };                  
         }
          String [] tabloBaslik = new String[] {"İşlem ID","Kişi Adı", "Kitap Adı", "Emanet Tarihi", "İade Tarihi"};
          TableModel tabloModeli=new DefaultTableModel( veriler, tabloBaslik );                                                
          odunc_tablo.setModel(tabloModeli);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        odunc_tablo = new javax.swing.JTable();
        buton_iade = new javax.swing.JButton();
        OduncVer = new javax.swing.JButton();

        odunc_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        odunc_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                odunc_tabloMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(odunc_tablo);

        buton_iade.setText("İADE AL");
        buton_iade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buton_iadeActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        OduncVer.setText("ÖDÜNÇ VER");
        OduncVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OduncVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(OduncVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_iade)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buton_iade)
                    .addComponent(OduncVer))
                .addGap(0, 27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buton_iadeActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_buton_iadeActionPerformed
        // TODO add your handling code here:
        Odunc iadeislemi = new Odunc();
            try {
                iadeislemi.iadeal(seciliIslemID);
                tabloYenile();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_buton_iadeActionPerformed

    private void odunc_tabloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odunc_tabloMousePressed
        // TODO add your handling code here:
        seciliSatirSirasi = odunc_tablo.getSelectedRow();
        seciliIslemID = odunc_tablo.getValueAt(seciliSatirSirasi, 0).toString();
        System.out.println(seciliIslemID);        
    }//GEN-LAST:event_odunc_tabloMousePressed

    private void OduncVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OduncVerActionPerformed
        // TODO add your handling code here:
         try {
            OduncVer odunc= new OduncVer(this);
            odunc.pack();
            odunc.setLocationRelativeTo(null);
            odunc.setVisible(true);
            odunc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_OduncVerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OduncVer;
    private javax.swing.JButton buton_iade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable odunc_tablo;
    // End of variables declaration//GEN-END:variables
}
