/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import model.Kisi;
import model.Kitap;
import model.Odunc;

/**
 *
 * @author msi
 */

public class OduncVer extends javax.swing.JFrame {

    OduncPanel oduncPanel;
    
    public OduncVer(OduncPanel oduncPanel) throws Exception {
        
        ImageIcon img = new ImageIcon("C:\\Users\\Lenovo\\Desktop\\kutuphaneotomasyonu\\src\\main\\java\\view\\kutuphaneIcon.png");
        this.setIconImage(img.getImage());
        this.setTitle("Ödünç İşlemleri");
        initComponents();
        this.oduncPanel = oduncPanel;
        
         //Kitapları listeleme
        Kitap O_Kitap = new Kitap();
        ArrayList<Kitap> kitaplar = O_Kitap.listele();
        DefaultListModel listModelKitap = new DefaultListModel ();
        for (int i = 0; i < kitaplar.size(); i++) {
            listModelKitap.addElement(kitaplar.get(i).kitapID+"-"+kitaplar.get(i).kitapAdi);
        }
        OduncKitapListe.setModel(listModelKitap);
        
        //Kişileri listeleme
        Kisi O_Kisi= new Kisi();
        ArrayList<Kisi> kisi=O_Kisi.listele();
        DefaultListModel listModelKisi = new DefaultListModel();
        for (int i = 0; i < kisi.size(); i++) {
             listModelKisi.addElement(kisi.get(i).kisiID+"-"+kisi.get(i).kisiAdi+" "+kisi.get(i).kisiSoyadi);
        }
        OduncKisiListe.setModel(listModelKisi);
    }
    /**
     * Creates new form OduncVer
     */
    public OduncVer() throws Exception {
        ImageIcon img = new ImageIcon("C:\\Users\\Lenovo\\Desktop\\kutuphaneotomasyonu\\src\\main\\java\\view\\kutuphaneIcon.png");
        this.setIconImage(img.getImage());
        this.setTitle("Ödünç İşlemleri");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OduncKisiListe = new javax.swing.JList<>();
        buton_odunc_ver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OduncKitapListe = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("KİTAP ADI");
        jLabel1.setFocusTraversalPolicyProvider(true);

        jLabel2.setText("KİŞİ ADI");

        OduncKisiListe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(OduncKisiListe);

        buton_odunc_ver.setText("ÖDÜNÇ VER");
        buton_odunc_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buton_odunc_verActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        OduncKitapListe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(OduncKitapListe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(buton_odunc_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(20, 20, 20)
                .addComponent(buton_odunc_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_odunc_verActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_buton_odunc_verActionPerformed
        // TODO add your handling code here:

        String secili_kitap= OduncKitapListe.getSelectedValue();
        String secili_kisi=OduncKisiListe.getSelectedValue();
        String OduncKisi[] = secili_kisi.split("-");
        String OduncKitap[]=secili_kitap.split("-");

        Odunc odunc_islemi =new Odunc();
        try {
            odunc_islemi.oduncver(Integer.parseInt(OduncKisi[0]), Integer.parseInt(OduncKitap[0]));
            System.out.println("Kitap başarıyla eklendi..");
            oduncPanel.tabloYenile();
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buton_odunc_verActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OduncVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OduncVer().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(OduncVer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> OduncKisiListe;
    private javax.swing.JList<String> OduncKitapListe;
    private javax.swing.JButton buton_odunc_ver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
